!function(a, b, c) {
    var d;
    (a.raid_effect_buff = function(b, d, e) {
        this.initialize(b, d, e, {}), this.frame_0 = function() {
            this.stop()
        }, this.timeline.addTween(c.Tween.get(this).call(this.frame_0).wait(1)), this.raid_effect_buff = new a.mc_raid_effect_buff_root, this.raid_effect_buff.setTransform(427, 405, 1, 1, 0, 0, 0, 427, 405), this.timeline.addTween(c.Tween.get({}).to({state: [{t: this.raid_effect_buff}]}).wait(2))
    }).prototype = d = new c.MovieClip, d.nominalBounds = new c.Rectangle(0, 0, 698, 764), (a.raid_effect_buff01 = function() {
        this.sourceRect = new c.Rectangle(218, 2, 175, 176), this.initialize(b.raid_effect_buff)
    }).prototype = d = new c.Bitmap, d.nominalBounds = new c.Rectangle(0, 0, 175, 176), (a.raid_effect_buff02 = function() {
        this.sourceRect = new c.Rectangle(2, 2, 214, 448), this.initialize(b.raid_effect_buff)
    }).prototype = d = new c.Bitmap, d.nominalBounds = new c.Rectangle(0, 0, 214, 448), (a.raid_effect_buff04 = function() {
        this.sourceRect = new c.Rectangle(218, 180, 74, 198), this.initialize(b.raid_effect_buff)
    }).prototype = d = new c.Bitmap, d.nominalBounds = new c.Rectangle(0, 0, 74, 198), (a.raid_effect_buff_colar = function() {
        this.initialize(), this.shape = (new c.Shape).setTransform(0, 0, 1, 1), this.shape.graphics.f("#00FFE9").s().p("EhCuA72MAAAh3sMCFcAAAMAAAB3sg"), this.shape.setTransform(427, 383), this.addChild(this.shape)
    }).prototype = d = new c.Container, d.nominalBounds = new c.Rectangle(0, 0, 854, 766), (a.mc_raid_effect_buff04 = function() {
        this.initialize(), this.instance = new a.raid_effect_buff04, this.addChild(this.instance)
    }).prototype = d = new c.Container, d.nominalBounds = new c.Rectangle(0, 0, 74, 198), (a.mc_raid_effect_buff02 = function() {
        this.initialize(), this.instance = new a.raid_effect_buff02, this.addChild(this.instance)
    }).prototype = d = new c.Container, d.nominalBounds = new c.Rectangle(0, 0, 214, 448), (a.mc_raid_effect_buff01 = function(b, d, e) {
        this.initialize(b, d, e, {}), this.frame_0 = function() {
            this.compositeOperation = "lighter"
        }, this.timeline.addTween(c.Tween.get(this).call(this.frame_0)), this.instance = new a.raid_effect_buff01, this.instance.setTransform(-87, -176), this.timeline.addTween(c.Tween.get({}).to({state: [{t: this.instance}]}).wait(1))
    }).prototype = d = new c.MovieClip, d.nominalBounds = new c.Rectangle(-87, -176, 175, 176), (a.mc_raid_effect_buff04_m = function(b, d, e) {
        this.initialize(b, d, e, {}), this.instance = new a.mc_raid_effect_buff04, this.instance.setTransform(16, -86), this.instance.alpha = .199, this.instance._off = !0, this.timeline.addTween(c.Tween.get(this.instance).wait(8).to({_off: !1}, 0).to({scaleY: 1.23,y: -145,alpha: 1}, 2).to({scaleX: .71,scaleY: 2.35,x: 27,y: -508}, 8).to({scaleX: .54,scaleY: 2.74,x: 33,y: -654,alpha: .199}, 4).to({_off: !0}, 1).wait(1)), this.instance_1 = new a.mc_raid_effect_buff04, this.instance_1.setTransform(-19, 162, .568, .568), this.instance_1.alpha = .199, this.instance_1._off = !0, this.timeline.addTween(c.Tween.get(this.instance_1).wait(6).to({_off: !1}, 0).to({scaleY: .7,y: 128,alpha: .699}, 2).to({scaleX: .4,scaleY: 1.33,x: -12,y: -78}, 8).to({scaleX: .31,scaleY: 1.56,x: -9,y: -161,alpha: .199}, 4).to({_off: !0}, 1).wait(3)), this.instance_2 = new a.mc_raid_effect_buff04, this.instance_2.setTransform(71, 194), this.instance_2.alpha = .199, this.instance_2._off = !0, this.timeline.addTween(c.Tween.get(this.instance_2).wait(4).to({_off: !1}, 0).to({scaleY: 1.23,y: 135,alpha: 1}, 2).to({scaleX: .71,scaleY: 2.35,x: 82,y: -229}, 8).to({scaleX: .54,scaleY: 2.74,x: 88,y: -374,alpha: .199}, 4).to({_off: !0}, 1).wait(5)), this.instance_3 = new a.mc_raid_effect_buff04, this.instance_3.setTransform(145, -36, .719, .719), this.instance_3.alpha = .199, this.instance_3._off = !0, this.timeline.addTween(c.Tween.get(this.instance_3).wait(2).to({_off: !1}, 0).to({scaleY: .88,y: -79,alpha: .699}, 2).to({scaleX: .51,scaleY: 1.69,x: 153,y: -340}, 8).to({scaleX: .39,scaleY: 1.97,x: 158,y: -445,alpha: .199}, 4).to({_off: !0}, 1).wait(7)), this.instance_4 = new a.mc_raid_effect_buff04, this.instance_4.setTransform(-82, 61), this.instance_4.alpha = .199, this.timeline.addTween(c.Tween.get(this.instance_4).to({scaleY: 1.23,y: 2,alpha: 1}, 2).to({scaleX: .71,scaleY: 2.35,x: -71,y: -362}, 8).to({scaleX: .54,scaleY: 2.74,x: -65,y: -507,alpha: .199}, 4).to({_off: !0}, 1).wait(9))
    }).prototype = d = new c.MovieClip, d.nominalBounds = new c.Rectangle(-82, 61, 74, 198), (a.mc_raid_effect_buff = function(b, d, e) {
        this.initialize(b, d, e, {}), this.frame_1 = function() {
            require(["lib/sound"], function(a) {
                a.play("se/ab_0060_se_1.mp3")
            })
        }, this.frame_14 = function() {
            this.stop()
        }, this.timeline.addTween(c.Tween.get(this).wait(1).call(this.frame_1).wait(13).call(this.frame_14)), this.instance = new a.raid_effect_buff_colar, this.instance.setTransform(320, 327, .749, .854, 0, 0, 0, 427, 383), this.instance.alpha = 0, this.instance.compositeOperation = "lighter", this.timeline.addTween(c.Tween.get(this.instance).to({alpha: .102}, 2).wait(8).to({alpha: 0}, 4).wait(1)), this.instance_1 = new a.mc_raid_effect_buff04_m, this.instance_1.setTransform(464, 150, 1, 1, 0, 0, 0, 48, -355), this.instance_1.alpha = .199, this.instance_1.compositeOperation = "lighter", this.timeline.addTween(c.Tween.get(this.instance_1).to({y: -9,alpha: 1}, 3).wait(7).to({y: -249,alpha: .199}, 3).to({_off: !0}, 1).wait(1)), this.instance_2 = new a.mc_raid_effect_buff01, this.instance_2.setTransform(432, 410, 1.068, 1, 0, 180, 0, 0, -88), this.instance_2.alpha = .5, this.instance_2.compositeOperation = "lighter", this.instance_2._off = !0, this.timeline.addTween(c.Tween.get(this.instance_2).wait(7).to({_off: !1}, 0).wait(1).to({x: 425,y: 375,alpha: 1}, 0).to({scaleX: 1.48,scaleY: 1.5,skewX: 175.5,x: 450,y: 52,alpha: 0}, 6).wait(1)), this.instance_3 = new a.mc_raid_effect_buff01, this.instance_3.setTransform(548, 537, 1, 1, 0, 0, 0, 0, -88), this.instance_3.alpha = .5, this.instance_3.compositeOperation = "lighter", this.instance_3._off = !0, this.timeline.addTween(c.Tween.get(this.instance_3).wait(5).to({_off: !1}, 0).wait(1).to({y: 510,alpha: 1}, 0).to({scaleX: 1.2,scaleY: 1.2,skewX: -1.1,x: 548,y: 290,alpha: 0}, 6).to({_off: !0}, 1).wait(2)), this.instance_4 = new a.mc_raid_effect_buff01, this.instance_4.setTransform(443, 422, 1, 1, 0, 0, 0, 0, -88), this.instance_4.alpha = .5, this.instance_4.compositeOperation = "lighter", this.instance_4._off = !0, this.timeline.addTween(c.Tween.get(this.instance_4).wait(2).to({_off: !1}, 0).wait(1).to({y: 395,alpha: 1}, 0).to({scaleX: 1.2,scaleY: 1.2,skewX: -1.1,x: 443,y: 175,alpha: 0}, 6).to({_off: !0}, 1).wait(5)), this.instance_5 = new a.mc_raid_effect_buff01, this.instance_5.setTransform(553, 372, 1, 1, 0, 0, 0, 0, -88), this.instance_5.alpha = .5, this.instance_5.compositeOperation = "lighter", this.timeline.addTween(c.Tween.get(this.instance_5).wait(1).to({y: 345,alpha: 1}, 0).to({scaleX: 1.2,scaleY: 1.2,skewX: -1.1,x: 553,y: 125,alpha: 0}, 6).to({_off: !0}, 1).wait(7)), this.instance_6 = new a.mc_raid_effect_buff02, this.instance_6.setTransform(483, 412, 2.01, 1.545, 0, 0, 0, 107, 224), this.instance_6.alpha = .398, this.timeline.addTween(c.Tween.get(this.instance_6).to({y: 358,alpha: 1}, 3).to({scaleX: 2.94,scaleY: 2.26,x: 483,y: 187}, 7).to({scaleX: 3.21,scaleY: 2.47,x: 483,y: -26,alpha: .102}, 3).to({_off: !0}, 1).wait(1))
    }).prototype = d = new c.MovieClip, d.nominalBounds = new c.Rectangle(0, 0, 698, 764), (a.mc_raid_effect_buff_root = function(b, d, e) {
        this.initialize(b, d, e, {}), this.frame_0 = function() {
            this.raid_effect_buff_end.gotoAndPlay(0)
        }, this.frame_6 = function() {
            this.stop()
        }, this.timeline.addTween(c.Tween.get(this).call(this.frame_0).wait(6).call(this.frame_6)), this.raid_effect_buff_end = new a.mc_raid_effect_buff, this.raid_effect_buff_end.setTransform(9, 9, 1, 1, 0, 0, 0, 9, 9), this.timeline.addTween(c.Tween.get({}).to({state: [{t: this.raid_effect_buff_end}]}).wait(7))
    }).prototype = d = new c.MovieClip, d.nominalBounds = new c.Rectangle(0, 0, 698, 764)
}(lib = lib || {}, images = images || {}, createjs = createjs || {});
var lib, images, createjs;
